# CHANGEME: Set these variable to your liking
title: Relay add on Module for Seeed Studio XIAO Firmware Flasher
description: Powered by Seeed Studio, ESPHome and ESP Web Tools
theme: jekyll-theme-slate
